import { ComboBox, LineEdit, VerticalBox, Button, TextEdit } from "std-widgets.slint";
import { MyComboBox, MySpinBox } from "../common.slint";
import { IconButton } from "../widgets/icon_button.slint";
import { TextButton } from "../widgets/text_button.slint";
import { Icons, FontSettings, TodoPalette, SpaceSettings } from "../widgets/styling.slint";
import { FrequencyPresetAdapter } from "../adapters/frequency_adapter.slint";
import { FrequencyPresetSlintStruct } from "../adapters/frequency_adapter.slint";

// @rust-attr(derive(serde::Serialize, serde::Deserialize))
// export struct FrequencyPresetSlintStruct {
//     preset_name: string,
//     preset_desc: string,
//     preset_details: string,
//     checked: bool,
//     freq1: float,
//     freq2: float,
//     freq3: string,
// }

// export global FrequencyPresetAdapter {
//     in-out property <int> index;  /* row if we are editing */
//     in-out property <string> mode: "Create";  /* changes to Update if we are editing */
//     in-out property <FrequencyPresetSlintStruct> preset;  /* changes to Update if we are editing */
//     // in-out property <string> preset-name: 0;
//     // in-out property <string> preset-desc: 0;
//     // in-out property <float> freq1: 0;
//     // in-out property <float> freq2: 0;
//     // in-out property <string> freq3: "";

//     // callback create(
//     //     /* preset-name */ string, 
//     //     /* preset-desc */ string, 
//     //     /* freq1 */ float,
//     //     /* freq2 */ float,
//     //     /* freq3_csv_list */ string,
//     //     );
//     // callback update(
//     //     /* index */ int, 
//     //     /* preset-name */ string, 
//     //     /* preset-desc */ string, 
//     //     /* freq1 */ float,
//     //     /* freq2 */ float,
//     //     /* freq3_csv_list */ string,
//     //     );
//     callback create(
//         /* preset */ FrequencyPresetSlintStruct, 
//         );
//     callback update(
//         /* index */ int, 
//         /* preset */ FrequencyPresetSlintStruct, 
//         );
//     callback back();
//     pure callback validate_preset-name(string) -> bool;
//     pure callback validate_freq3(string) -> bool;

// }

export component CreateFrequencyPresetView {
    callback cancel_operation();
    callback create_frequency_preset();
    callback update_frequency_preset();
    callback changed_field(string, string) -> bool;
    callback changed_float(string, float) -> bool;
    in-out property <int> index;
    in-out property <string> display_mode: "Create";
    in-out property <FrequencyPresetSlintStruct> preset;

    property <string> preset-name-label: "Name";
    property <string> preset-name-desc: "Description";
    property <string> freq1_label: "Frequency1";
    property <string> freq2_label: "Frequency2";
    property <string> freq3_label: "Frequency3";

    VerticalBox {
        padding: 10px;
        alignment: start;
         HorizontalLayout {
            IconButton {
                icon: Icons.close;
                accessible-label: @tr("Cancel Operation");

                clicked => {
                    cancel_operation();
                }
            }

            // spacer
            Rectangle { }


            Button {
                text: FrequencyPresetAdapter.mode;
                enabled: preset-name-input.text != "";
                primary: true;

                clicked => {
                    if display_mode == "Create" {
                        create_frequency_preset();
                    } else {
                        create_frequency_preset();
                    }
                }
            }
        }

        VerticalLayout {
            spacing: SpaceSettings.default-spacing;

            preset-name-label := Text {
                text: @tr("FrequencyPreset name");
                color: TodoPalette.foreground;
                font-size: FontSettings.body-strong.font-size;
                font-weight: FontSettings.body-strong.font-weight;
                horizontal-alignment: left;
                overflow: elide;
            }

            Rectangle { } // spacer
            preset-name-input := LineEdit {
                text: FrequencyPresetAdapter.preset.preset-name;
                placeholder-text: @tr("FrequencyPreset Name (alphanumber, underscore, hyphen)");
                changed text => {
                    changed_field("preset_name", self.text);
                }              
            }

            preset-desc-label := Text {
                text: @tr("FrequencyPreset Description");
                color: TodoPalette.foreground;
                font-size: FontSettings.body-strong.font-size;
                font-weight: FontSettings.body-strong.font-weight;
                horizontal-alignment: left;
                overflow: elide;
            }

            Rectangle { } // spacer
            preset-desc-input := LineEdit {
                text: FrequencyPresetAdapter.preset.preset-desc;
                placeholder-text: @tr("FrequencyPreset Description");
                changed text => {
                    changed_field("preset_desc", self.text);
                }               
            }

            freq1_label := Text {
                text: @tr("FrequencyPreset1");
                color: TodoPalette.foreground;
                font-size: FontSettings.body-strong.font-size;
                font-weight: FontSettings.body-strong.font-weight;
                horizontal-alignment: left;
                overflow: elide;
            }
            Rectangle { } // spacer
            freq1-input := MySpinBox {
                value: FrequencyPresetAdapter.preset.freq1;
                minimum: -34.5;
                maximum: 34.5;
                changed value => {
                    changed_float(self.name, self.value);
                }               
            }

            freq2_label := Text {
                text: @tr("FrequencyPreset1");
                color: TodoPalette.foreground;
                font-size: FontSettings.body-strong.font-size;
                font-weight: FontSettings.body-strong.font-weight;
                horizontal-alignment: left;
                overflow: elide;
            }
            Rectangle { } // spacer
            freq2-input := MySpinBox {
                value: FrequencyPresetAdapter.preset.freq2;
                minimum: -34.5;
                maximum: 34.5;
                changed value => {
                    changed_float(self.name, self.value);
                }               
            }

            freq3_label := Text {
                text: @tr("FrequencyPreset3");
                color: TodoPalette.foreground;
                font-size: FontSettings.body-strong.font-size;
                font-weight: FontSettings.body-strong.font-weight;
                horizontal-alignment: left;
                overflow: elide;
            }
            Rectangle { } // spacer
            freq3-input := TextEdit {
                text: FrequencyPresetAdapter.preset.freq3;
                changed text => {
                    changed_field("freq3", self.text);
                }              
            }

            Rectangle { }
        }
    }
}
