import { ComboBox, LineEdit, VerticalBox, Button, SpinBox } from "std-widgets.slint";
import { MyComboBox, MySpinBox } from "../common.slint";
import { IconButton } from "../widgets/icon_button.slint";
import { TextButton } from "../widgets/text_button.slint";
import { Icons, FontSettings, TodoPalette, SpaceSettings } from "../widgets/styling.slint";
// import { CreateFrequencyPresetAdapter } from "create_frequency_preset_view.slint";
import { PowerPresetAdapter } from "../adapters/power_adapter.slint";


// @rust-attr(derive(serde::Serialize, serde::Deserialize))
// export struct PowerPresetSlintStruct {
//     preset_name: string,
//     preset_desc: string,
//     preset_details: string,
//     checked: bool,
//     power1: float,
//     power2: float,
//     power3: float,
//     power4: float,
//     power5: float,
//     power6: float,
//     power7: float,
//     power8: float,
//     power9: int,
//     power10: int,
// }

// export global CreatePowerPresetAdapter {
//     in-out property <int> index;  /* row if we are editing */
//     in-out property <string> mode: "Create";  /* changes to Update if we are editing */
//     in-out property <PowerPresetSlintStruct> preset;  /* changes to Update if we are editing */

//     // in-out property <float> power2: 0;
//     // in-out property <float> power3: 0;
//     // in-out property <float> power4: 0;
//     // in-out property <float> power5: 0;
//     // in-out property <float> power6: 0;
//     // in-out property <float> power7: 0;
//     // in-out property <float> power8: 0;
//     // in-out property <int> power9: 0;
//     // in-out property <int> power10: 0;

//     // in-out property <string> preset-name: 0;
//     // in-out property <string> preset-desc: 0;
//     // in-out property <float> power1: 0;
//     // in-out property <float> power2: 0;
//     // in-out property <float> power3: 0;
//     // in-out property <float> power4: 0;
//     // in-out property <float> power5: 0;
//     // in-out property <float> power6: 0;
//     // in-out property <float> power7: 0;
//     // in-out property <float> power8: 0;
//     // in-out property <int> power9: 0;
//     // in-out property <int> power10: 0;

//     // callback create(
//     //     /* preset-name */ string, 
//     //     /* preset-desc */ string, 
//     //     /* power1 */ float,
//     //     /* power2 */ float,
//     //     /* power3 */ float,
//     //     /* power4 */ float,
//     //     /* power5 */ float,
//     //     /* power6 */ float,
//     //     /* power7 */ float,
//     //     /* power8 */ float,
//     //     /* power9 */ int,
//     //     /* power10 */ int, );

//     // callback update(
//     //     /* index */ int, 
//     //     /* preset-name */ string, 
//     //     /* preset-desc */ string, 
//     //     /* power1 */ float,
//     //     /* power2 */ float,
//     //     /* power3 */ float,
//     //     /* power4 */ float,
//     //     /* power5 */ float,
//     //     /* power6 */ float,
//     //     /* power7 */ float,
//     //     /* power8 */ float,
//     //     /* power9 */ int,
//     //     /* power10 */ int, );

//     callback create(
//         /* preset */ PowerPresetSlintStruct 
//        );

//     callback update(
//         /* index */ int, 
//         /* preset */ PowerPresetSlintStruct 
//        );

//     // function edit(
//     //     xreset_name: string, 
//     //     // preset-desc: string, 
//     //     // xower1: float,
//     //     // power2: float,
//     //     // power3: float,
//     //     // power4: float,
//     //     // power5: float,
//     //     // power6: float,
//     //     // power7: float,
//     //     // power8: float,
//     //     // power9: int,
//     //     // power10: int, 
//     //     ) {
//     //         preset-name = xreset_name;
//     // }
//     callback back();
//     pure callback validate_preset-name(string) -> int;

//     public function change_preset_desc(value: string) {
//         preset.preset-desc = value;
//     }
//     public function change_preset_name(value: string) {
//         preset.preset-name = value;
//     }
//     public function change_power1(value: float) {
//         preset.power1 = value;
//     }
//     public function change_power2(value: float) {
//         preset.power2 = value;
//     }
//     public function change_power3(value: float) {
//         preset.power4 = value;
//     }
//     public function change_power4(value: float) {
//         preset.power4 = value;
//     }
//     public function change_power5(value: float) {
//         preset.power5 = value;
//     }
//     public function change_power6(value: float) {
//         preset.power6 = value;
//     }
//     public function change_power7(value: float) {
//         preset.power7 = value;
//     }
//     public function change_power8(value: float) {
//         preset.power8 = value;
//     }
//     public function change_power9(value: float) {
//         preset.power9 = value;
//     }
//     public function change_power10(value: float) {
//         preset.power10 = value;
//     }
// }

export component CreatePowerPresetView {
    property <string> preset-name-label: "Name";
    property <string> preset-name-desc: "Description";
    property <string> valid_power1_label: "Power1";
    property <string> valid_power2_label: "Power2";
    property <string> valid_power3_label: "Power3";
    property <string> valid_power4_label: "Power4";
    property <string> valid_power5_label: "Power5";
    property <string> valid_power6_label: "Power6";
    property <string> valid_power7_label: "Power7";
    property <string> valid_power8_label: "Power8";
    property <string> valid_power9_label: "Power9";
    property <string> valid_power10_label: "Power10";

    VerticalBox {
        padding: 10px;
        alignment: start;
        HorizontalLayout {
            IconButton {
                icon: Icons.close;
                accessible-label: @tr("Cancel Operation");

                clicked => {
                    root.reset();
                    PowerPresetAdapter.back();
                }
            }

            // spacer
            Rectangle { }

            Button {
                text: PowerPresetAdapter.mode;
                enabled: preset-name-input.text != "";
                primary: true;

                clicked => {
                    if PowerPresetAdapter.mode == "Create" {
                        root.create();
                    } else {
                        root.update();
                    }
                }
            }
        }

        VerticalLayout {
            spacing: SpaceSettings.default-spacing;

            preset-name-label := Text {
                text: @tr("PowerPreset name");
                color: TodoPalette.foreground;
                font-size: FontSettings.body-strong.font-size;
                font-weight: FontSettings.body-strong.font-weight;
                horizontal-alignment: left;
                overflow: elide;
            }

            Rectangle { } // spacer
            preset-name-input := LineEdit {
                text: PowerPresetAdapter.preset.preset-name;
                placeholder-text: @tr("PowerPreset Name (alphanumber, underscore, hyphen)");
                accessible-label: preset-name-label.text;
                changed text => {
                    PowerPresetAdapter.change_preset_name(self.text);
                }
            }

            preset-desc-label := Text {
                text: @tr("PowerPreset Description");
                color: TodoPalette.foreground;
                font-size: FontSettings.body-strong.font-size;
                font-weight: FontSettings.body-strong.font-weight;
                horizontal-alignment: left;
                overflow: elide;
            }

            Rectangle { } // spacer
            preset-desc-input := LineEdit {
                text: PowerPresetAdapter.preset.preset-desc;
                placeholder-text: @tr("PowerPreset Description");
                accessible-label: preset-desc-label.text;
                changed text => {
                    PowerPresetAdapter.change_preset_desc(self.text);
                }
            }

            GridLayout {
                Row {
                    VerticalLayout {
                        power1-label := Text {
                            text: @tr("PowerPreset1");
                            color: TodoPalette.foreground;
                            font-size: FontSettings.body-strong.font-size;
                            font-weight: FontSettings.body-strong.font-weight;
                            horizontal-alignment: left;
                            overflow: elide;
                        }

                        Rectangle { } // spacer
                        power1-input := MySpinBox {
                            value: PowerPresetAdapter.preset.power1;
                            minimum: -34.5;
                            maximum: 34.5;
                            // accessible-label: power1-label.text;
                            changed value => {
                                PowerPresetAdapter.change_power1(self.value);
                                validate();
                            }
                            // width: 150px;
                        }
                    }

                    Rectangle { } // spacer
                    VerticalLayout {
                        power2-label := Text {
                            text: @tr("PowerPreset2");
                            color: TodoPalette.foreground;
                            font-size: FontSettings.body-strong.font-size;
                            font-weight: FontSettings.body-strong.font-weight;
                            horizontal-alignment: left;
                            overflow: elide;
                        }

                        Rectangle { } // spacer
                        power2-input := MySpinBox {
                            value: PowerPresetAdapter.preset.power2;
                            minimum: -34.5;
                            maximum: 34.5;
                            // accessible-label: power2-label.text;
                            changed value => {
                                PowerPresetAdapter.change_power2(self.value);
                                validate();
                            }
                            // width: 150px;
                        }
                    }
                }

                Row {
                    VerticalLayout {
                        power3-label := Text {
                            text: @tr("PowerPreset3");
                            color: TodoPalette.foreground;
                            font-size: FontSettings.body-strong.font-size;
                            font-weight: FontSettings.body-strong.font-weight;
                            horizontal-alignment: left;
                            overflow: elide;
                        }

                        Rectangle { } // spacer
                        power3-input := MySpinBox {
                            value: PowerPresetAdapter.preset.power3;
                            minimum: -34.5;
                            maximum: 34.5;
                            // accessible-label: power3-label.text;
                            changed value => {
                                PowerPresetAdapter.change_power3(self.value);
                                validate();
                            }
                            // width: 150px;
                        }
                    }

                    Rectangle { } // spacer
                    VerticalLayout {
                        power4-label := Text {
                            text: @tr("PowerPreset4");
                            color: TodoPalette.foreground;
                            font-size: FontSettings.body-strong.font-size;
                            font-weight: FontSettings.body-strong.font-weight;
                            horizontal-alignment: left;
                            overflow: elide;
                        }

                        Rectangle { } // spacer
                        power4-input := MySpinBox {
                            value: PowerPresetAdapter.preset.power4;
                            minimum: -34.5;
                            maximum: 34.5;
                            // accessible-label: power4-label.text;
                            changed value => {
                                PowerPresetAdapter.change_power4(self.value);
                                validate();
                            }
                            // width: 150px;
                        }
                    }
                }

                Row {
                    VerticalLayout {
                        power5-label := Text {
                            text: @tr("PowerPreset5");
                            color: TodoPalette.foreground;
                            font-size: FontSettings.body-strong.font-size;
                            font-weight: FontSettings.body-strong.font-weight;
                            horizontal-alignment: left;
                            overflow: elide;
                        }

                        Rectangle { } // spacer
                        power5-input := MySpinBox {
                            value: PowerPresetAdapter.preset.power5;
                            minimum: -34.5;
                            maximum: 34.5;
                            // accessible-label: power5-label.text;
                            changed value => {
                                PowerPresetAdapter.change_power5(self.value);
                                validate();
                            }
                        }
                    }

                    Rectangle { } // spacer
                    VerticalLayout {
                        power6-label := Text {
                            text: @tr("PowerPreset6");
                            color: TodoPalette.foreground;
                            font-size: FontSettings.body-strong.font-size;
                            font-weight: FontSettings.body-strong.font-weight;
                            horizontal-alignment: left;
                            overflow: elide;
                        }

                        Rectangle { } // spacer
                        power6-input := MySpinBox {
                            value: PowerPresetAdapter.preset.power6;
                            minimum: -34.5;
                            maximum: 34.5;
                            // accessible-label: power6-label.text;
                            changed value => {
                                PowerPresetAdapter.change_power6(self.value);
                                validate();
                            }
                            // width: 150px;
                        }
                    }
                }

                Row {
                    VerticalLayout {
                        power7-label := Text {
                            text: @tr("PowerPreset7");
                            color: TodoPalette.foreground;
                            font-size: FontSettings.body-strong.font-size;
                            font-weight: FontSettings.body-strong.font-weight;
                            horizontal-alignment: left;
                            overflow: elide;
                        }

                        Rectangle { } // spacer
                        power7-input := MySpinBox {
                            value: PowerPresetAdapter.preset.power7;
                            minimum: -34.5;
                            maximum: 34.5;
                            // accessible-label: power7-label.text;
                            changed value => {
                                PowerPresetAdapter.change_power7(self.value);
                                validate();
                            }
                        }
                    }

                    Rectangle { } // spacer
                    VerticalLayout {
                        power8-label := Text {
                            text: @tr("PowerPreset8");
                            color: TodoPalette.foreground;
                            font-size: FontSettings.body-strong.font-size;
                            font-weight: FontSettings.body-strong.font-weight;
                            horizontal-alignment: left;
                            overflow: elide;
                        }

                        Rectangle { } // spacer
                        power8-input := MySpinBox {
                            value: PowerPresetAdapter.preset.power8;
                            minimum: -34.5;
                            maximum: 34.5;
                            // accessible-label: power8-label.text;
                            changed value => {
                                PowerPresetAdapter.change_power8(self.value);
                                validate();
                            }
                            // width: 150px;
                        }
                    }
                }

                Row {
                    VerticalLayout {
                        power9-label := Text {
                            text: @tr("PowerPreset9");
                            color: TodoPalette.foreground;
                            font-size: FontSettings.body-strong.font-size;
                            font-weight: FontSettings.body-strong.font-weight;
                            horizontal-alignment: left;
                            overflow: elide;
                        }

                        Rectangle { } // spacer
                        power9-input := MySpinBox {
                            value: PowerPresetAdapter.preset.power9;
                            minimum: -34.5;
                            maximum: 34.5;
                            // accessible-label: power9-label.text;
                            changed value => {
                                PowerPresetAdapter.change_power9(self.value);
                                validate();
                            }
                        }
                    }

                    Rectangle { } // spacer
                    VerticalLayout {
                        power10-label := Text {
                            text: @tr("PowerPreset10");
                            color: TodoPalette.foreground;
                            font-size: FontSettings.body-strong.font-size;
                            font-weight: FontSettings.body-strong.font-weight;
                            horizontal-alignment: left;
                            overflow: elide;
                        }

                        Rectangle { } // spacer
                        power10-input := MySpinBox {
                            value: PowerPresetAdapter.preset.power10;
                            minimum: -34.5;
                            maximum: 34.5;
                            // accessible-label: power10-label.text;
                            changed value => {
                                PowerPresetAdapter.change_power10(self.value);
                                validate();
                            }
                            // width: 150px;
                        }
                    }
                }
            }

            Rectangle { }
        }
    }

    function reset() {
        preset-name-input.text = "";
        preset-desc-input.text = "";
        power1-input.value = 0;
        power2-input.value = 0;
        power3-input.value = 0;
        power4-input.value = 0;
        power5-input.value = 0;
        power6-input.value = 0;
        power7-input.value = 0;
        power8-input.value = 0;
        power9-input.value = 0;
        power10-input.value = 0;
    }

    function update() {
        PowerPresetAdapter.back();
        // PowerPresetAdapter.update(
        //     PowerPresetAdapter.index,
        //     preset-name-input.text, 
        //     preset-desc-input.text, 
        //     power1-input.value, 
        //     power2-input.value, 
        //     power3-input.value, 
        //     power4-input.value, 
        //     power5-input.value, 
        //     power6-input.value, 
        //     power7-input.value, 
        //     power8-input.value, 
        //     power9-input.value, 
        //     power10-input.value);
        PowerPresetAdapter.update(
            PowerPresetAdapter.index,
            PowerPresetAdapter.preset);
        root.reset();
    }

    function create() {
        PowerPresetAdapter.back();
        // PowerPresetAdapter.create(
        //     preset-name-input.text, 
        //     preset-desc-input.text, 
        //     power1-input.value, 
        //     power2-input.value, 
        //     power3-input.value, 
        //     power4-input.value, 
        //     power5-input.value, 
        //     power6-input.value, 
        //     power7-input.value, 
        //     power8-input.value, 
        //     power9-input.value, 
        //     power10-input.value);
        PowerPresetAdapter.create(
            PowerPresetAdapter.preset);
        root.reset();
    }

    function validate() {
        debug("checking valid values power1:"+power1-input.value+" > "+power1-input.minimum + " < " + power1-input.maximum);
        if power1-input.value < power1-input.minimum || power1-input.value > power1-input.maximum {
            power1-label.text = valid_power1_label + "[invalid value]";
        } else {
            power1-label.text = valid_power1_label + "foo";
        }
        if power2-input.value < power2-input.minimum || power2-input.value > power2-input.maximum {
            power2-label.text = valid_power2_label + "[invalid value]";
        } else {
            power2-label.text = valid_power2_label;
        }
        if power3-input.value < power3-input.minimum || power3-input.value > power3-input.maximum {
            power3-label.text = valid_power3_label + "[invalid value]";
        } else {
            power3-label.text = valid_power3_label;
        }
        if power4-input.value < power4-input.minimum || power4-input.value > power4-input.maximum {
            power4-label.text = valid_power4_label + "[invalid value]";
        } else {
            power4-label.text = valid_power4_label;
        }
        if power5-input.value < power5-input.minimum || power5-input.value > power5-input.maximum {
            power5-label.text = valid_power5_label + "[invalid value]";
        } else {
            power5-label.text = valid_power5_label;
        }
        if power6-input.value < power6-input.minimum || power6-input.value > power6-input.maximum {
            power6-label.text = valid_power6_label + "[invalid value]";
        } else {
            power6-label.text = valid_power6_label;
        }
        if power7-input.value < power7-input.minimum || power7-input.value > power7-input.maximum {
            power7-label.text = valid_power7_label + "[invalid value]";
        } else {
            power7-label.text = valid_power7_label;
        }
        if power8-input.value < power8-input.minimum || power8-input.value > power8-input.maximum {
            power8-label.text = valid_power8_label + "[invalid value]";
        } else {
            power8-label.text = valid_power8_label;
        }
        if power9-input.value < power9-input.minimum || power9-input.value > power9-input.maximum {
            power9-label.text = valid_power9_label + "[invalid value]";
        } else {
            power9-label.text = valid_power9_label;
        }
        if power10-input.value < power10-input.minimum || power10-input.value > power10-input.maximum {
            power10-label.text = valid_power10_label + "[invalid value]";
        } else {
            power10-label.text = valid_power10_label;
        }
    }
}
