// import { MissionListView, MissionListAdapter } from "./views/mission_list_view.slint";
import { MissionListView } from "./views/mission_list_view.slint";
// export { MissionListAdapter }

import { CreateMissionView } from "./views/create_mission_view.slint";
import { MissionAdapter, MissionSlintStruct } from "./adapters/mission_adapter.slint";
export { MissionAdapter }

import { PowerPresetListView, PowerPresetListAdapter } from "./views/power_preset_list_view.slint";
export { PowerPresetListAdapter }

import { CreatePowerPresetView } from "./views/create_power_preset_view.slint";
import { PowerPresetAdapter } from "./adapters/power_adapter.slint";
export { PowerPresetAdapter }

import { FrequencyPresetListView } from "./views/frequency_preset_list_view.slint";
import { FrequencyPresetListAdapter } from "./views/frequency_preset_list_view.slint";
export { FrequencyPresetListAdapter }

import { CreateFrequencyPresetView } from "./views/create_frequency_preset_view.slint";
import { FrequencyPresetAdapter } from "./adapters/frequency_adapter.slint";
export { FrequencyPresetAdapter }

import { TaskListView, TaskListAdapter } from "./views/task_list_view.slint";
export { TaskListAdapter }

import { CreateTaskView, CreateTaskAdapter } from "./views/create_task_view.slint";
export { CreateTaskAdapter }

import { AnimationSettings } from "./widgets/styling.slint";
import { Tabs } from "tabs.slint";
import { TabWidget } from "std-widgets.slint";
import { Tab1 } from "tab1.slint";


export component MainWindow inherits Window {
    preferred-width: 600px;
    preferred-height: 600px;
    title: "Radio Configuration Tool";
    in-out property <string> mission_mode;
    in-out property <int> mission_index;
    in-out property <bool> show_mission_list: true;
    in-out property <[MissionSlintStruct]> missions: [
        // this is only dummy data for the preview
        { mission_name: "dummy_mission1", mission_desc: "mission#1", mission_id: 1, mission_details: "Nominal|band1" },
        { mission_name: "dummy_mission2", mission_desc: "mission#2", mission_id: 2, mission_details: "Nominal|band2" },
        { mission_name: "dummy_mission3", mission_desc: "mission#3", mission_id: 3, mission_details: "Nominal|band3" },
    ];
    in-out property <MissionSlintStruct> mission: { mission_name: "mission?", mission_desc: "mission#1", mission_id: 1, mission_details: "Nominal|band1" };

    callback create_mission();
    callback update_mission();
    // callback changed_field(string, string) -> bool;
    callback s2r_check_mission_field(MissionSlintStruct, string, string) -> MissionSlintStruct;
    callback s2r_create_mission(MissionSlintStruct);
    callback s2r_update_mission(int, MissionSlintStruct);

    // Tabs {}
    TabWidget {
        // Tab {
        //     title: "General";
        //     Tab1 {}
        // }
        Tab {
            title: "Missions";
            Rectangle {
                if show_mission_list  : mission_list_view := MissionListView {
                    missions <=> missions;
                    width: 100%;
                    height: 100%;
                    show_edit_mission(idx) => {
                        debug("Edit mission", idx);
                        mission_index = idx;
                        mission = missions[idx];
                        debug("Edit mission", mission);
                        show_mission_list = false;
                        mission_mode = "Update";
                    }
                    show_create_mission => {
                        show_mission_list = false;
                        mission_mode = "Create";
                    }
                }

                if !show_mission_list  : create_mission_view := CreateMissionView {
                    mode <=> mission_mode;
                    mission <=> mission;
                    width: 100%;
                    height: 100%;
                    cancel_operation => {
                        show_mission_list = true;
                    }
                    create_mission => {
                        debug("index.slint create mission", mission);
                        s2r_create_mission(mission);
                        show_mission_list = true;
                    }
                    update_mission => {
                        debug("index.slint update mission", mission);
                        s2r_update_mission(mission_index, mission);
                        show_mission_list = true;
                    }
                    changed_field(field_name, value) => {
                        debug("index.slint update mission", mission);
                        mission = s2r_check_mission_field(mission, field_name, value);
                        return true;
                    }
                }
            }
        }
        // Tab {
        //     title: "Power Presets";
        //     Rectangle {
        //         // border-color: yellow;
        //         // border-width: 10px;
        //         // padding: 30px;
        //         x: -(PowerPresetNavigationAdapter.current-page * root.width);
        //         width: 2 * root.width;

        //         // if self.x > -root.width : MissionListView {
        //         if PowerPresetNavigationAdapter.current-page == 0  : PowerPresetListView {
        //             x: 0 + 10px;
        //             y: 10px;
        //             // padding: 20px;
        //             width: root.width - 20px;
        //             height: root.height - 35px;
        //         }

        //         // if self.x < 0 : CreateMissionView {
        //         if PowerPresetNavigationAdapter.current-page == 1  : CreatePowerPresetView {
        //             x: root.width + 20px;
        //             y: 10px;
        //             width: root.width - 40px;
        //             height: root.height - 35px;
        //         }

        //         animate x {
        //             duration: AnimationSettings.move-duration;
        //             easing: AnimationSettings.move-easing;
        //         }
        //     }
        // }
        // Tab {
        //     title: "Frequency Presets";
        //     Rectangle {
        //         // border-color: yellow;
        //         // border-width: 10px;
        //         // padding: 30px;
        //         x: -(FrequencyPresetNavigationAdapter.current-page * root.width);
        //         width: 2 * root.width;

        //         // if self.x > -root.width : MissionListView {
        //         if FrequencyPresetNavigationAdapter.current-page == 0  : FrequencyPresetListView {
        //             x: 0 + 10px;
        //             y: 10px;
        //             // padding: 20px;
        //             width: root.width - 20px;
        //             height: root.height - 35px;
        //         }

        //         // if self.x < 0 : CreateMissionView {
        //         if FrequencyPresetNavigationAdapter.current-page == 1  : CreateFrequencyPresetView {
        //             x: root.width + 20px;
        //             y: 10px;
        //             width: root.width - 40px;
        //             height: root.height - 35px;
        //         }

        //         animate x {
        //             duration: AnimationSettings.move-duration;
        //             easing: AnimationSettings.move-easing;
        //         }
        //     }
        // }
        // Tab {
        //     title: "Test Tasks";
        //     Rectangle {
        //         // border-color: yellow;
        //         // border-width: 10px;
        //         // padding: 30px;
        //         x: -(NavigationAdapter.current-page * root.width);
        //         width: 2 * root.width;

        //         // if self.x > -root.width : TaskListView {
        //         if NavigationAdapter.current-page == 0  : TaskListView {
        //             x: 0 + 10px;
        //             y: 10px;
        //             // padding: 20px;
        //             width: root.width - 20px;
        //             height: root.height - 35px;
        //         }

        //         // if self.x < 0 : CreateTaskView {
        //         if NavigationAdapter.current-page == 1  : CreateTaskView {
        //             x: root.width + 20px;
        //             y: 10px;
        //             width: root.width - 40px;
        //             height: root.height - 35px;
        //         }

        //         animate x {
        //             duration: AnimationSettings.move-duration;
        //             easing: AnimationSettings.move-easing;
        //         }
        //     }
        // }
    }

}
