import { SpinBox, Slider, Button, StandardButton, Switch, ComboBox, StandardListView, CheckBox, TabWidget, StandardButton, LineEdit, ScrollView } from "std-widgets.slint";
import { Tab1 } from "tab1.slint";
import { Tab2 } from "tab2.slint";
import { TaskListView } from "views/task_list_view.slint";
//v2

export component Tabs inherits Rectangle {
    ///width: 430px;
    preferred-width: 600px;
    preferred-height: 600px;
    background: #061029;
    // title: "Radio Config Tool";
//
    callback save_clicked();

    // ScrollView {
    //     width: parent.width;
    //     height: parent.height;
    //     viewport-width: 600px;
    //     viewport-height: 600px;
        

        // Rectangle {
        //     width: 100%;
        //     height: 100%;
        //     preferred-height: 100%;
        //     preferred-width: 100%;
        //     border-color: white;
        //     border-width: 1px;
            TabWidget {
                // width: 430px;
                // height: 330px;
                Tab {
                    title: "General";
                    Tab1 {}
                }

                Tab {
                        padding: 20px;
                        //         x: 0;
                    // width: 100%;
                    // height: root.height;
                    title: "Radios";
                    // width: 
                    Rectangle {
                        // vertical-stretch: 1;
                        // horizontal-stretch: 1;
                        padding: 20px;
                        preferred-height: 400px;
                        preferred-width: 400px;
                        border-color: yellow;
                        border-width: 10px;
                        width: 100%;
                        height: 100%;
                        TaskListView {}
                    }
                }

                Tab {
                    title: "Tab3";
                }
            }
        // }

        // property <string> density: "light";
        // property <int> density-value: 1;
        // property <string> name: "ZZZZZ";
        // property <int> age:22;
        // property <string> gender: "Male";
        // property <string> status: "Active";
        // property <string> age_error;
        // property <int> valid-age;
        // callback check-age(int);
        // check-age(age) => {
        //     if (age > 65 || age < 18){
        //        age_label.text = "Age(18-65)";
        //        age_label.color = Colors.red;
        //     } else {
        //         age_label.text = "Age(18-65)";
        //         age_label.color = Colors.white;
        //     }
        // }
    // }
}
